### ISSUE TITLE
Gray line in DropGem semicircle

### ISSUE THREAD

**Issue by okg00dbye** [hansel-app/hansel#102]
anyone else sees this
![image](https://user-images.githubusercontent.com/59867654/134525892-30c33539-3677-4531-a1ec-41579bdf8c6b.png)

**Comment by sebastiantoh** [comment]
is that the scrollbar..., but yep i see that too

**Comment by ming-00** [comment]
aye so what was it

**Comment by sebastiantoh** [comment]
> aye so what was it

i think it is the scrollbar haha
