### ISSUE TITLE
[Pickup Gem] video blacks out after it finishes playing?

### ISSUE THREAD

**Issue by okg00dbye** [hansel-app/hansel#131]
![image](https://user-images.githubusercontent.com/59867654/134568492-103427c0-c15f-4d28-bfd9-83685ed86d8b.png)

**Comment by ming-00** [comment]
:0 which gem video is this? it doesn’t happen for me

**Comment by okg00dbye** [comment]
blue but uhm I suspect it has something to do with me injecting mock data, can close this if no one else faces the same

**Comment by ming-00** [comment]
aye i think blue's last frame is black D: i crop

**Comment by sebastiantoh** [comment]
> aye i think blue's last frame is black D: i crop

oops sorry

**Comment by ming-00** [comment]
> oops sorry

my bad... i didn't shorten frames when i removed some from the glitching :/
