### ISSUE TITLE
Throw error if google api key is empty

### ISSUE THREAD

**Issue by okg00dbye** [hansel-app/hansel#132]

**Comment by ianyong** [comment]
Is there a need to? If the Google API key isn't set, it's quite obvious (and probably preferable to the entire app just not working).

**Comment by okg00dbye** [comment]
The app will stop working in other places uhh this reminds me of smth i say in tele

**Comment by ianyong** [comment]
> The app will stop working in other places uhh this reminds me of smth i say in tele

Ah, I see. Anyway this can be low priority since our deployment setup already inserts the key.

**Comment by okg00dbye** [comment]
Closing~
