### ISSUE TITLE
Clicking on hamburger menu in deployed site makes it disappear

### ISSUE THREAD

**Issue by okg00dbye** [hansel-app/hansel#143]
![image](https://user-images.githubusercontent.com/59867654/134610140-bbd0ee26-03dc-4270-a1ec-2d0ae78c9b89.png)

**Comment by ming-00** [comment]
what the heck... I just tried on mobile and it doesnt disappear for me D:

**Comment by sebastiantoh** [comment]
I got this same error earlier this morning, but now I cannot reproduce it. Might be some caching going on... Try clearing everything?

**Comment by ianyong** [comment]
The previous deployment was fairly old. (I've since deployed the latest changes on master around 10 minutes ago.) Guess we can KIV this for now?

**Comment by ming-00** [comment]
resolved?
