### ISSUE TITLE
Should display hamburger menu when offline/ map doesn't load

### ISSUE THREAD

**Issue by okg00dbye** [hansel-app/hansel#64]
![image](https://user-images.githubusercontent.com/59867654/134341523-4a740cb2-7fe2-4d7a-a33c-d90a410ccc25.png)
so that user can still access offline functionality of viewing gem logs

**Comment by ming-00** [comment]
Oh yea... + the loading should change message if there's no permission for geolocation/ if offline

**Comment by okg00dbye** [comment]
Not sure which PR fixed this, but seems like it's fixed
