### ISSUE TITLE
Onboarding screen after registration

### ISSUE THREAD

**Issue by okg00dbye** [hansel-app/hansel#71]

**Comment by sebastiantoh** [comment]
what does this entail? In the interest of time, I'm wondering if we can omit this and just have users customise their profiles (if they want to in the original profile page)

**Comment by okg00dbye** [comment]
Maybe just one overlay explaining the app, eg
![image](https://user-images.githubusercontent.com/59867654/134451969-73e6334e-37fa-482c-92c4-a4bb876345de.png)

**Comment by okg00dbye** [comment]
tq seb!
