### ISSUE TITLE
Border around map

### ISSUE THREAD

**Issue by ianyong** [hansel-app/hansel#82]
![image](https://user-images.githubusercontent.com/5585517/134474634-816a7e28-2d9a-44f6-b2a8-d34245636194.png)

**Comment by ianyong** [comment]
Weirdly enough, I cannot replicate this. Guess we can close this if no one else encounters this.

**Comment by sebastiantoh** [comment]
Cannot replicate as well

**Comment by ianyong** [comment]
> Cannot replicate as well

Nice, closing this.
