### ISSUE TITLE
Frequency of Popup

### ISSUE THREAD

**Issue by okg00dbye** [hansel-app/hansel#97]
![image](https://user-images.githubusercontent.com/59867654/134505247-8e51e292-c54f-4507-9de1-13b990e68971.png)
maybe displaying every time we return to the map is too much, instead only when user first log in, not sure

**Comment by sebastiantoh** [comment]
I've set it so that the home screen will only appear when ever the user opens the app (rather than when they first log in, cos i don't think they will log in often)
